# -*- coding: utf-8 -*-
"""firstTraining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kj2VEN_W91pQOSqVU8oIBeZbB0HOg1yv
"""

#!pip3 install https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl

'''
from google.colab import drive
drive.mount('/content/drive')
'''

cd content/drive/My Drive/Colab Notebooks

from imageai.Prediction.Custom import ModelTraining

model_trainer = ModelTraining()

model_trainer.setModelTypeAsResNet()

model_trainer.setDataDirectory("idenprof")

model_trainer.trainModel(num_objects=10, num_experiments=200, enhance_data=True, batch_size=32, show_network_summary=True)

